server:
  port: 8096

spring:
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: sa
    password:

  h2:
    console:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      dialect: org.hibernate.dialect.H2Dialect